name: buildViaCI

permissions:
  contents: write

on:
  push:
    paths:
      - EmeraldGraphics/EmeraldGraphics/**
      - kern_start.cpp
      - kern_start.hpp
  pull_request:
    paths:
      - EmeraldGraphics/EmeraldGraphics/**
      - kern_start.cpp
      - kern_start.hpp
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT
  ACID32: 1

jobs:
  build:
    name: Build
    runs-on: macos-15
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/royalgraphx/ocbuild/refs/heads/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - run: git submodule init
      - run: git submodule update
      - run: xcodebuild -jobs 1 -configuration Debug -arch ACID32 -arch x86_64
      - run: xcodebuild -jobs 1 -configuration Release -arch ACID32 -arch x86_64

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/*/*.zip
      
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true